/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import core.PFReader;
import core.XMLReader;
import core.model.Mapa;
import core.search.AStar;
import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import ui.swing.MapRenderer;
import ui.utils.ColorController;
import ui.webLaf.PSOutTabbedPaneUI;
import ui.webLaf.WeblafUtils;

/**
 *
 * @author lite
 */
public class MainWindow extends javax.swing.JFrame {
    Mapa mapa;
    /**
     * Creates new form MainWIndow
     */
    public MainWindow() {
        initComponents();
        configureTheme();
    }
    private void configureTheme(){
        WeblafUtils.instalaWeblaf();
        WeblafUtils.configuraWeblaf(jPanel2);
        WeblafUtils.configuraWebLaf(jTextArea1);
        WeblafUtils.configuraWebLaf(jScrollPane1);
        jTabbedPane1.setUI(new PSOutTabbedPaneUI());
        WeblafUtils.configurarBotao(webButton5, ColorController.COR_DESTAQUE, ColorController.COR_LETRA);
        WeblafUtils.configurarBotao(webButton4, ColorController.COR_DESTAQUE, ColorController.COR_LETRA);
        WeblafUtils.configurarBotao(webButton1, ColorController.COR_DESTAQUE, ColorController.COR_LETRA);
        WeblafUtils.configurarBotao(webButton2, ColorController.COR_PRINCIPAL, ColorController.COR_LETRA,ColorController.PROGRESS_BAR, Color.orange, 5);
        WeblafUtils.configurarBotao(webButton3, ColorController.COR_PRINCIPAL, ColorController.COR_LETRA,ColorController.FUNDO_CLARO, Color.orange, 5);
        
        jPanel2.setBackground(ColorController.COR_PRINCIPAL);
        jTextArea1.setBackground(ColorController.COR_PRINCIPAL);
        jTextArea1.setForeground(ColorController.COR_LETRA);
        jPanel3.setBackground(ColorController.COR_PRINCIPAL); 
        jTabbedPane1.setForeground(ColorController.COR_LETRA);        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        labelURl = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        webButton3 = new com.alee.laf.button.WebButton();
        webButton2 = new com.alee.laf.button.WebButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        webButton1 = new com.alee.laf.button.WebButton();
        webButton4 = new com.alee.laf.button.WebButton();
        webButton5 = new com.alee.laf.button.WebButton();
        jSplitPane1 = new javax.swing.JSplitPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 5));
        jPanel3.setPreferredSize(new java.awt.Dimension(45, 45));
        jPanel3.setLayout(new java.awt.BorderLayout());

        labelURl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelURl.setForeground(new java.awt.Color(250, 250, 250));
        labelURl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelURl.setText("Peth Finder");
        jPanel3.add(labelURl, java.awt.BorderLayout.CENTER);

        jPanel4.setOpaque(false);
        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 5, 0));

        webButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/resources/window_min.png"))); // NOI18N
        webButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                webButton3ActionPerformed(evt);
            }
        });
        jPanel4.add(webButton3);

        webButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/resources/window_close.png"))); // NOI18N
        webButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                webButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(webButton2);

        jPanel3.add(jPanel4, java.awt.BorderLayout.EAST);

        getContentPane().add(jPanel3, java.awt.BorderLayout.NORTH);

        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanel2.setMinimumSize(new java.awt.Dimension(640, 480));
        jPanel2.setPreferredSize(new java.awt.Dimension(640, 480));
        jPanel2.setLayout(new java.awt.BorderLayout(20, 20));

        jPanel5.setOpaque(false);
        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Raio", "Gulosa" }));
        jPanel5.add(jComboBox1);

        webButton1.setText("Carregar PF");
        webButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                webButton1ActionPerformed(evt);
            }
        });
        jPanel5.add(webButton1);

        webButton4.setText("Carregar XML");
        webButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                webButton4ActionPerformed(evt);
            }
        });
        jPanel5.add(webButton4);

        webButton5.setText("Calcular");
        webButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                webButton5ActionPerformed(evt);
            }
        });
        jPanel5.add(webButton5);

        jPanel2.add(jPanel5, java.awt.BorderLayout.SOUTH);

        jSplitPane1.setDividerLocation(450);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Courier New", 0, 13)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTabbedPane1.addTab("Console", jScrollPane1);

        jSplitPane1.setBottomComponent(jTabbedPane1);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jSplitPane1.setLeftComponent(jLabel1);

        jPanel2.add(jSplitPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void webButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_webButton3ActionPerformed
        setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_webButton3ActionPerformed

    private void webButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_webButton2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_webButton2ActionPerformed

    private void webButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_webButton4ActionPerformed
        mapa = XMLReader.lerXML();
        Image image= MapRenderer.getInstance().getFirstImage(mapa);
        jLabel1.setIcon(new ImageIcon(image));
    }//GEN-LAST:event_webButton4ActionPerformed

    private void webButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_webButton1ActionPerformed
        mapa = PFReader.lerPF();
        Image image= MapRenderer.getInstance().getFirstImage(mapa);
        jLabel1.setIcon(new ImageIcon(image));
        
    }//GEN-LAST:event_webButton1ActionPerformed

    private void webButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_webButton5ActionPerformed
        if(mapa!=null){
            mapa.setPathMatrix(AStar.getInstance().getPath(mapa,jComboBox1.getSelectedItem().toString()));
            jTextArea1.setText(AStar.getInstance().getConsoleLog());
            TableModel model = new DefaultTableModel(AStar.getInstance().getCosts(), new String[]{" - "," - "," - "," - "," - "," - "," - "," - "," - "," - "," - "," - "," - "," - "," - "});
            if(mapa.getPathMatrix()!=null){
                Image image= MapRenderer.getInstance().getPathedImage(mapa);
                jLabel1.setIcon(new ImageIcon(image));
            }
        }
    }//GEN-LAST:event_webButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel labelURl;
    private com.alee.laf.button.WebButton webButton1;
    private com.alee.laf.button.WebButton webButton2;
    private com.alee.laf.button.WebButton webButton3;
    private com.alee.laf.button.WebButton webButton4;
    private com.alee.laf.button.WebButton webButton5;
    // End of variables declaration//GEN-END:variables
}
